###
GET http://127.0.0.1:8000/owners/

###
POST http://127.0.0.1:8000/owners/
Content-Type: application/json

{
    "first_name": "Граф",
    "last_name": "Дракула"
}

###
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Зомби Снежок",
    "color": "White",
    "birth_year": 1901,
    "owner": 1,
    "achievement_name": [
        {"name": "поймал мышку"},
        {"name": "разбил вазу"}
    ]
} 


###
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Бездельник",
    "color": "Whites",
    "birth_year": 2017,
    "owner": 1
} 

###
GET http://127.0.0.1:8000/cats/


###
GET http://127.0.0.1:8000/cats/recent-white-cats/