###
GET http://127.0.0.1:8000/owners/

###
POST http://127.0.0.1:8000/owners/
Content-Type: application/json

{
    "first_name": "Theodor",
    "last_name": "Voland"
}

###
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Барсик",
    "color": "White",
    "birth_year": 2017,
    "owner": 1,
    "achievements": [
        {"name": "поймал мышку"},
        {"name": "разбил вазу"}
    ]
} 


###
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Бездельник",
    "color": "Прозрачный синий",
    "birth_year": 2017,
    "owner": 1
} 

###
GET http://127.0.0.1:8000/cats/8/
