# Generated by Django 3.2 on 2022-12-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20221208_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='owne',
            new_name='owner',
        ),
    ]
